### ISSUE TITLE
Write down business requirements for module "View"

### ISSUE THREAD

**Issue by brain545** [brain545/view#1]

**Comment by sanikeev** [comment]
Когда планируешь собрать первоначальный список требований?

**Comment by brain545** [comment]
> Когда планируешь собрать первоначальный список требований?
На этой неделе будет список (первая версия) для обсуждения.

**Comment by sanikeev** [comment]
Все еще жду список, хочется уже начать...

**Comment by deslum** [comment]
Ты вообще больше всех ныл, что в отпуск хочешь. Сиди в отпуске, отдыхай

**Comment by deslum** [comment]
Нельзя просто так взять и начать. Идет работа по оценке и проработке требований. Не мешай. Скоро все будет.
